"""Compiled substrate — AUTO-GENERATED by tbox_compiler.py.

Source: data/tbox/tworoom.ttl  (OWL TBox, K_spec knowledge source)
Compiler: stable_worldmodel/wm/substrate/tbox_compiler.py
Target: Two-Room planning environment dynamics

DO NOT EDIT BY HAND — regenerate with:
  python -m stable_worldmodel.wm.substrate.tbox_compiler --write

This file is the artefact produced by the knowledge compilation step
in the Executable World Models framework.  It is functionally identical
to python_substrate.py, which was written manually. The equivalence is
verified by the --verify flag.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional

import numpy as np

# ── Compiled constants (from :TwoRoomDefault individual in tworoom.ttl) ──
IMG_SIZE     = 224
BORDER_SIZE  = 14
WALL_CENTER  = 112
WALL_AXIS    = 1       # 1 = vertical wall
WALL_THICK   = 10
MAX_DOOR     = 3
AGENT_RADIUS = 7.0
AGENT_SPEED  = 5.0
DOOR_HALF    = 14.0
DOOR_MARGIN  = 1.75

# ── Derived constants ──────────────────────────────────────────────────
EFF_LOW   = WALL_CENTER - WALL_THICK // 2 - AGENT_RADIUS   # 100.0
EFF_HIGH  = WALL_CENTER + WALL_THICK // 2 + AGENT_RADIUS   # 124.0
CLIP_LO   = BORDER_SIZE + AGENT_RADIUS                      # 21.0
CLIP_HI   = IMG_SIZE - BORDER_SIZE - AGENT_RADIUS           # 203.0
DOOR_BAND = DOOR_HALF + DOOR_MARGIN                         # 15.75
PUSH_L    = EFF_LOW  - 0.5   # 99.5
PUSH_R    = EFF_HIGH + 0.5   # 124.5

# ── ABox (compiled from class + property declarations) ─────────────────

@dataclass
class TwoRoomABox:
    """Scene state for one or many parallel Two-Room episodes.

    Compiled from :Agent, :Target, :Wall, :Door class declarations
    in the OWL TBox.  Arrays are (..., d) shaped; leading dims
    propagate through rollout().
    """
    agent_pos:        np.ndarray   # (..., 2)
    target_pos:       np.ndarray   # (..., 2)
    door_centers:     np.ndarray   # (..., MAX_DOOR, 2)  zeros for unused
    agent_radius:     float = AGENT_RADIUS
    agent_speed:      float = AGENT_SPEED
    wall_axis:        int   = WALL_AXIS
    wall_thickness:   int   = WALL_THICK
    door_half_extents: tuple = (DOOR_HALF, DOOR_HALF, DOOR_HALF)
    num_doors:        int   = 1

    @classmethod
    def from_state_vec(
        cls,
        state: np.ndarray,
        *,
        agent_radius: float = AGENT_RADIUS,
        agent_speed: float = AGENT_SPEED,
        wall_axis: int = WALL_AXIS,
        wall_thickness: int = WALL_THICK,
        door_half_extents: tuple = (DOOR_HALF, DOOR_HALF, DOOR_HALF),
        num_doors: int = 1,
    ) -> "TwoRoomABox":
        assert state.shape[-1] == 10, state.shape
        return cls(
            agent_pos=state[..., 0:2].astype(np.float32, copy=True),
            target_pos=state[..., 2:4].astype(np.float32, copy=True),
            door_centers=state[..., 4:10].reshape(
                *state.shape[:-1], MAX_DOOR, 2
            ).astype(np.float32, copy=True),
            agent_radius=agent_radius,
            agent_speed=agent_speed,
            wall_axis=wall_axis,
            wall_thickness=wall_thickness,
            door_half_extents=door_half_extents,
            num_doors=num_doors,
        )

# ── R3 helper (door membership test) ─────────────────────────────────

def _in_any_door_1d(
    coord: np.ndarray,
    door_centers_1d: np.ndarray,
    half_extents: np.ndarray,
    num_doors: int,
    margin: float,
) -> np.ndarray:
    """Vectorised door-membership test. coord shape (...). Returns bool."""
    out = np.zeros_like(coord, dtype=bool)
    for i in range(num_doors):
        c = door_centers_1d[..., i]
        s = half_extents[i]
        out |= (coord >= c - s - margin) & (coord <= c + s + margin)
    return out

# ── step() — compiled from R1, R2, R3 rule individuals ───────────────

def step(abox: TwoRoomABox, action: np.ndarray) -> TwoRoomABox:
    """One compiled step: R1 MoveProposed + R2 CollideBorder + R3 CollideWall.

    Generated from rules:
      R1: new_pos = old_pos + clip(action, -1, 1) * speed
      R2: clamp position to [border+radius, img-border-radius]
      R3: block wall crossing unless agent is inside a door gap
    """
    # R1: MoveProposed  (rule expr: PROPOSED speed=5.0)
    action   = np.clip(action, -1.0, 1.0)
    proposed = abox.agent_pos + action * abox.agent_speed

    # R2: CollideBorder  (rule expr: CLIP_BORDER img_size=224 border_size=14 agent_radius=7.0)
    proposed = np.clip(proposed, CLIP_LO, CLIP_HI)

    # R3: CollideWall  (rule expr: WALL_COLL wall_axis=1 wall_center=112 wall_thickness=10 agent_radius=7.0 door_half_extent=14.0 door_margin=1.75 max_doors=3)
    half_extents = np.asarray(abox.door_half_extents, dtype=np.float32)

    if abox.wall_axis == 1:                           # vertical wall
        x_start = abox.agent_pos[..., 0]
        x_prop  = proposed[..., 0]
        y_prop  = proposed[..., 1]
        door_1d = abox.door_centers[..., :, 1]        # door y-coords
        in_door = _in_any_door_1d(
            y_prop, door_1d, half_extents,
            abox.num_doors, DOOR_MARGIN,
        )
        started_left = x_start < WALL_CENTER
        push_left  = started_left & (x_prop > EFF_LOW)  & ~in_door
        push_right = (~started_left) & (x_prop < EFF_HIGH) & ~in_door
        new_x = np.where(push_left,  PUSH_L,
                np.where(push_right, PUSH_R, x_prop))
        new_y = y_prop
    else:                                             # horizontal wall
        y_start = abox.agent_pos[..., 1]
        y_prop  = proposed[..., 1]
        x_prop  = proposed[..., 0]
        door_1d = abox.door_centers[..., :, 0]
        in_door = _in_any_door_1d(
            x_prop, door_1d, half_extents,
            abox.num_doors, DOOR_MARGIN,
        )
        started_top = y_start < WALL_CENTER
        push_top    = started_top  & (y_prop > EFF_LOW)  & ~in_door
        push_bottom = (~started_top) & (y_prop < EFF_HIGH) & ~in_door
        new_y = np.where(push_top,    PUSH_L,
                np.where(push_bottom, PUSH_R, y_prop))
        new_x = x_prop

    new_pos = np.stack([new_x, new_y], axis=-1).astype(np.float32)
    return TwoRoomABox(
        agent_pos=new_pos,
        target_pos=abox.target_pos,
        door_centers=abox.door_centers,
        agent_radius=abox.agent_radius,
        agent_speed=abox.agent_speed,
        wall_axis=abox.wall_axis,
        wall_thickness=abox.wall_thickness,
        door_half_extents=abox.door_half_extents,
        num_doors=abox.num_doors,
    )

# ── rollout() ─────────────────────────────────────────────────────────

def rollout(abox: TwoRoomABox, actions: np.ndarray) -> TwoRoomABox:
    """Run T compiled steps. actions shape (..., T, 2)."""
    T = actions.shape[-2]
    cur = abox
    for t in range(T):
        cur = step(cur, actions[..., t, :])
    return cur

# ── CompiledSubstrateCostModel — Costable protocol ────────────────────

class CompiledSubstrateCostModel:
    """Compiled substrate conforming to the Costable protocol.

    This is the Experiment B model: auto-generated from the OWL TBox
    without manual physics engineering.  Identical API to
    SubstrateCostModel (python_substrate.py).

    Parameters
    ----------
    door_y : float
        Door y-coordinate prior (θ_door).  Default 112 = wrong prior.
    """

    def __init__(self, door_y: float = 112.0):
        self.door_y = door_y

    def get_cost(self, info_dict: dict, action_candidates) -> "np.ndarray":
        """Costable.get_cost implementation.

        info_dict["observation"] : (B, S, T, 10)
        action_candidates        : (B, S, H, action_block * 2)
        Returns cost             : (B, S)
        """
        import torch
        obs = info_dict["observation"]
        if hasattr(obs, "numpy"):
            obs = obs.numpy()
        if hasattr(action_candidates, "numpy"):
            action_candidates = action_candidates.numpy()

        obs    = np.asarray(obs,    dtype=np.float32)
        acts   = np.asarray(action_candidates, dtype=np.float32)

        # Most-recent obs
        state = obs[..., -1, :]                       # (B, S, 10)
        B, S, _ = state.shape

        # Override door prior
        state[..., 5] = self.door_y                   # obs[5] = door_y

        abox = TwoRoomABox.from_state_vec(state)

        # Reshape actions: (B, S, H, block*2) → (B, S, H*block, 2)
        _B, _S, H, ad = acts.shape
        micro = acts.reshape(B, S, H * (ad // 2), 2)

        final = rollout(abox, micro)
        diff  = final.agent_pos - final.target_pos
        cost  = np.linalg.norm(diff, axis=-1).astype(np.float32)

        return torch.as_tensor(cost)

    def parameters(self):
        return iter([])


# ── DynamicSubstrateCostModel — info-controlled variant ──────────────────

class DynamicSubstrateCostModel:
    """Compiled substrate that reads door position from obs[5] at runtime.

    Unlike CompiledSubstrateCostModel, does NOT override the door prior.
    Both this model and neural baselines (LeWM, GCBC) observe identical
    runtime information — kills the structural knowledge confound.

    Used for Experiment A v2: information-controlled comparison.
    """

    def get_cost(self, info_dict: dict, action_candidates) -> "np.ndarray":
        import torch
        obs = info_dict["observation"]
        if hasattr(obs, "numpy"):
            obs = obs.numpy()
        if hasattr(action_candidates, "numpy"):
            action_candidates = action_candidates.numpy()

        obs  = np.asarray(obs,  dtype=np.float32)
        acts = np.asarray(action_candidates, dtype=np.float32)

        state = obs[..., -1, :]   # (B, S, 10) — use obs[5] as-is (true door_y)
        B, S, _ = state.shape

        abox = TwoRoomABox.from_state_vec(state)

        _B, _S, H, ad = acts.shape
        micro = acts.reshape(B, S, H * (ad // 2), 2)

        final = rollout(abox, micro)
        diff  = final.agent_pos - final.target_pos
        cost  = np.linalg.norm(diff, axis=-1).astype(np.float32)

        return torch.as_tensor(cost)

    def parameters(self):
        return iter([])
